config/routes.rb
Rails.application.routes.draw do
  # Root path
  root to: "pages#home"

  # User profile
  get '/user/:id', to: 'pages#user', as: 'user'

  # User's bookings path
  get '/user/:id/list_users', to: 'bookings#list_users', as: 'user_booking_list'




  # List of a user's republicas
  get '/republicas/user_republicas', to: 'republicas#user_republicas', as: 'user_republicas'

  # FaceBook connect callback
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Resources path
  resources :republicas do
    resources :bookings do
      member do
        get '/cancel', to: 'bookings#cancel_booking', as: 'cancel'
        get '/confirm', to: 'bookings#confirm_booking', as: 'confirm'
        get '/reject', to: 'bookings#reject_booking', as: 'reject'
      end
    end
  end

  mount Attachinary::Engine => "/attachinary"
end

app/models/republica.rb
class Republica < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_attachments :photos, maximum: 10


  validates :address, presence: true
 # validates :zip_code, presence: true
  validates :description, presence: true
  validates :vacancies, presence: true
  validates :city, presence: true
 # validates :country, presence: true
  validates :name, presence: true, uniqueness: {scope: :city}
  validates :photos, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/controllers/republicas_controller.rb
class RepublicasController < ApplicationController
  before_action :find_republica, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @results = Republica.where(city: params[:city])
    @republicas = Republica.where.not(latitude: nil, longitude: nil).where(city: params[:city])

    @hash = Gmaps4rails.build_markers(@republicas) do |republica, marker|
      marker.lat republica.latitude
      marker.lng republica.longitude
      # marker.infowindow render_to_string(partial: "/republicas/map_box", locals: { flat: flat })
    end
  end

  def user_republicas
    @republicas = current_user.republicas
  end

  def show
    @republica_coordinates = { lat: @republica.latitude, lng: @republica.longitude }
    @hash = Gmaps4rails.build_markers(@republica) do |republica, marker|
      marker.lat republica.latitude
      marker.lng republica.longitude
      # marker.infowindow render_to_string(partial: "/republicas/map_box", locals: { flat: flat })
    end
    @bookings = @republica.bookings
  end

  def new
    @republica = Republica.new
  end

  def create
    @republica = Republica.new(republica_params)
    @republica.user = current_user
    if @republica.save
      redirect_to republica_path(@republica)
    else
      render "new"
    end
  end

  def edit
  end

  def update
    @republica.update(republica_params)
    redirect_to republica_path(@republica)
  end

  def destroy
    @republica.destroy
    redirect_to republicas_path
  end

private

  def find_republica
    @republica = Republica.find(params[:id])
  end

  def republica_params
    params.require(:republica).permit(:name, :address, :description, :vacancies, :city, photos: [])
  end
end

app/helpers/republicas_helper.rb
module RepublicasHelper
end

app/views/republicas/_form.html.erb
<%= simple_form_for(@republica) do |f| %>
  <%= f.input :name, label: "Nome da Republica", placeholder: "Republica do Wagon" %>
  <%= f.input :address, label: "Rua", placeholder: "Rua Lisboa 890" %>
  <%= f.input :zip_code, label: "CEP", placeholder: "05413-000" %>
  <%= f.input :city, label: "Cidade", placeholder: "São Paulo" %>
  <%= f.input :country, label: "Pais", placeholder: "Brasil", as: :text %>
  <%= f.input :description, label: "Descrição", placeholder: "Descrição"%>
  <%= f.input :vacancies, label: "Vagas", placeholder: "1" %>
  <%= f.input :photos, as: :attachinary %>
  <%= f.button :submit, class: "btn btn-green btn-block"  %>
<% end %>

app/views/republicas/destroy.html.erb
<h1>Republicas#destroy</h1>
<p>Find me in app/views/republicas/destroy.html.erb</p>

app/views/republicas/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="box-generic" style="margin: 10px 0 10px 0;">
      <h2 class="text-center" style="margin-top: 5px;">Editar republica</h2>
        <%= render 'form' %> <br>
        <%= link_to 'Back', republicas_path, class: "btn btn-default btn-block" %>
      </div>
    </div>
  </div>
</div>

app/views/republicas/index.html.erb
<div class="index-container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <div class="box-generic">
        <% word = @results.length >= 2 ? 's' : '' %>
        <h4 class="text-center"><%= @results.length %> resultado<%= word %> de republicas em <%= params[:city] %></h4>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-xs-12 col-sm-7 col-sm-offset-1">
      <div class="republica-filter box-generic text-center">
        <h4 class="text-center">Filters</h4 class="text-center">
        <div class="btn btn-default btn-fourth">Filter 1</div>
        <div class="btn btn-default btn-fourth">Filter 2</div>
        <div class="btn btn-default btn-fourth">Filter 3</div>
        <div class="btn btn-default btn-fourth">Filter 4</div>
      </div>
      <br>
      <div class="search-results">
        <div class="card-container">
          <div class="row">
            <% @results.each do |republica| %>
              <div class="col-xs-12 col-sm-6">
                <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path republica.photos.first.path %>')">

                  <% if republica.user.photo? || republica.user.facebook_picture_url? %>
                    <div class="card-avatar">
                      <%= cl_image_tag avatar_image(republica.user), class: "avatar-bordered" %>
                    </div>
                  <%end%>
                  <div class="card-title"><%= republica.name %></div>
                  <%= link_to '', republica_path(republica), class: "card-link" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-3">
      <div class="box-generic" style="padding: 0">
        <div id="map" style="height: 600px"></div>
      </div>
    </div>
  </div>
</div>





<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>

app/views/republicas/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="box-generic" style="margin: 10px 0 10px 0;">
      <h2 class="text-center" style="margin-top: 5px;">Nova republica</h2>
        <%= render 'form' %> <br>
        <%= link_to 'Back', republicas_path, class: "btn btn-default btn-block" %>
      </div>
    </div>
  </div>
</div>

<%= content_for(:after_js) do %>
  <script src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyCGiTlkGdihtCVi-3eFPxSj_zpJFBuV4FQ"></script>
<% end %>

app/views/republicas/show.html.erb
<div class="gray-wrapper">
  <div class="container">
    <div class="media">

      <div class="media-body">
      <!--Information Republica-->
        <h3><%=@republica.name%></h3>
        <div class="showsocial">
          <ul  class="list-inline">
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
            <li><a href="#"><i class="fa fa-youtube"></i></a></li>
          </ul>
        </div>
        Address: <%= @republica.address %>
        <%= @republica.zip_code %> <br>
        <%= @republica.city %>, <%= @republica.country %>
        <br>
        <br>
        N° vacancies: <%= @republica.vacancies %>
        <div class="media-section">
          <%= link_to "Perfil do usuario", user_path(@republica.user), {class: "btn btn-green"} %>
        </div>
          <!--Box Photos-->
        <div class="media-section">
          <h3>Galeria</h3>

          <!--Caroussel-->
          <div id="carousel-example-generic" class="carousel slide">

            <ol class="carousel-indicators">
              <% @republica.photos.each_with_index do |photo,index| %>
                <div class="item ">
                  <% if index == 0 %>
                     <li data-target="#carousel-example-generic" data-slide-to="<%= index %>" class="active"></li>
                  <% else %>
                    <li data-target="#carousel-example-generic" data-slide-to="<%= index %>"></li>
                  <% end %>
                </div>
              <% end %>

            </ol>

            <div class="carousel-inner" role="listbox">



              <% @republica.photos.each_with_index do |photo,index| %>
                <% if index == 0 %>
                  <div class="item active">
                    <%= cl_image_tag photo.path%>
                  </div>
                <% else %>
                  <div class="item">
                    <%= cl_image_tag photo.path%>
                  </div>
                <% end %>
              <% end %>
            </div>

            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
              <span class="icon-prev" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
              <span class="icon-next" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>

        <div class="media-section">
          <h3>Descrição</h3>
          <%= @republica.description %>
        </div>
      </div>

      <div class="media-aside">
        <div class="media-section">
          <h3>Localização</h3>
          <div id="map" style="width: 100%; height: 300px;"></div>
          <% content_for(:after_js) do %>
            <%= javascript_tag do %>
              $(document).ready(function() {
                var handler = Gmaps.build('Google');
                handler.buildMap({ internal: { id: 'map' } }, function() {
                  markers = handler.addMarkers(<%= raw @hash.to_json %>);
                  handler.bounds.extendWith(markers);
                  handler.fitMapToBounds();
                  if (markers.length == 0) {
                    handler.getMap().setZoom(2);
                  } else if (markers.length == 1) {
                    handler.getMap().setZoom(14);
                  }
                });
              });
            <% end %>
          <% end %>
        </div>
        <div class="media-section">

          <h4>Olha perfils dos moradores</h4>
          <ul class="list-inline">
            <% @bookings.each do |booking| %>
              <li>
                <% if booking.user.photo? %>
                    <%= link_to user_path(booking.user) do %>
                      <%= cl_image_tag avatar_image(booking.user), width: 100, height: 100, crop: :fill, class:"avatar" %>
                      <% end %>
                    <%else%>
                      <% if booking.user.facebook_picture_url? %>
                          <%= link_to user_path(booking.user) do %>
                          <%= cl_image_tag avatar_image(booking.user), width: 60, height: 60, crop: :fill, class:"avatar" %>
                            <% end %>
                      <% end %>
                  <% end %>
              </li>
            <%end%>
          <br>
          <br>
          </ul>

        </div>
        <div class="media-section">
          <%= link_to 'Back', republicas_path, class: "btn btn-primary"  %>
          <%= link_to 'Book', new_republica_booking_path(@republica), class: "btn btn-green"  %>
        </div>
      </div>
    </div>
  </div>
</div>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      $('.carousel').carousel();
    });
  <% end %>
<% end %>

app/views/republicas/user_republicas.html.erb
<% if @republicas %>
  <div class="republicas-container">
  <% @republicas.each do |republica| %>
    <div class="republica-line">
      <div class="republica-image">
      <% if republica.photos.first.present? %>
        <%= cl_image_tag republica.photos[0].path, width: 250, height: 150, crop: :fill %>
      <% end %>
      </div>
      <div class="republica-content text-center">
        <strong><%= republica.name %> </strong> <br>
        Cidade: <%= republica.city %>
      </div>
      <div class="republica-actions text-center">
        <%= link_to "Mostrar bookings", republica_bookings_path(republica), class: "btn btn-green"  %>
        <%= link_to "Mostrar republica", republica_path(republica), class: "btn btn-default"  %>
        <%= link_to "Editar", edit_republica_path(republica), class: "btn btn-default"  %>
      </div>
    </div>
  <% end %>
  </div>
<% else %>
  <h3>Voce ainda nao tem republicas no site!</h3>
<% end %>