config/routes.rb
Rails.application.routes.draw do
  # Root path
  root to: "pages#home"

  # User profile
  get '/user/:id', to: 'pages#user', as: 'user'

  # User's bookings path
  get '/user/:id/list_users', to: 'bookings#list_users', as: 'user_booking_list'




  # List of a user's republicas
  get '/republicas/user_republicas', to: 'republicas#user_republicas', as: 'user_republicas'

  # FaceBook connect callback
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Resources path
  resources :republicas do
    resources :bookings do
      member do
        get '/cancel', to: 'bookings#cancel_booking', as: 'cancel'
        get '/confirm', to: 'bookings#confirm_booking', as: 'confirm'
        get '/reject', to: 'bookings#reject_booking', as: 'reject'
      end
    end
  end

  mount Attachinary::Engine => "/attachinary"
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :republica

  validates :check_in, presence: true
  validates :check_out, presence: true
  validates :status, presence: true

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_booking, only: [:show, :edit, :update, :destroy, :confirm_booking, :reject_booking, :cancel_booking]
  before_action :set_republica, only: [:show, :edit, :confirm_booking, :reject_booking]
  before_action :find_republica, only: [:new, :create, :index, :update, :destroy]

  def index
    @bookings = @republica.bookings

  end

  def show
  end

  # GET /bookings/new
  def new
    @booking = @republica.bookings.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  def create
    @booking = @republica.bookings.new(booking_params)
    @booking.status = "P"
    @booking.user = current_user

    if @booking.save
      redirect_to user_booking_list_path(@booking.id, @booking.republica), notice: 'Booking was successfully created.'
    else
      render :new
    end

  end

  # PATCH/PUT /bookings/1
  def update
    @booking.status = "P"
    @booking.update(booking_params)
    redirect_to user_booking_list_path(@booking.id, @booking.republica_id), notice: 'Booking was successfully updated.'

  end

  def cancel_booking
    @booking.update_attributes(status: "C")
    redirect_to user_booking_list_path(@booking.id, @booking.republica_id), notice: 'Booking was successfully cancelated.'
  end

  # DELETE /bookings/1
  def destroy
    @booking.destroy
      redirect_to bookings_url, notice: 'Booking was successfully destroyed.'
  end

  def list_users
    @user = User.find(current_user)
    @bookings = @user.bookings
  end

  def confirm_booking
    if @republica.vacancies == 0
      redirect_to republica_bookings_path(@booking.republica_id), notice: 'No bed available.'
    end

    @booking.republica.vacancies -= 1
    @republica.save
    @booking.status = "A"
    @booking.save
    redirect_to republica_bookings_path(@booking.republica_id), notice: 'Booking acceped.'
  end

  def reject_booking
    if @booking.status == "A"
      @booking.republica.vacancies += 1
      @republica.save
    end

    @booking.status = "R"
    @booking.save
    redirect_to republica_bookings_path(@booking.republica_id), notice: 'Booking Rejected.'
  end

  private

    def find_republica
      @republica = Republica.find(params[:republica_id])

    end

    def set_republica

      @republica = @booking.republica

    end

    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:check_in, :check_out, :status, :user_id, :republica_id)
    end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@republica, @booking] do |f| %>
  <%= f.error_notification %>
  <%= f.input :check_in, as: :string, input_html: { "data-provide" => 'datepicker' } %>
  <%= f.input :check_out, as: :string, input_html: { "data-provide" => 'datepicker' } %>
  <%= f.button :submit, class: "btn btn-block btn-green" %>
<% end %>

app/views/bookings/destroy.html.erb
<h1>Destroy</h1>

app/views/bookings/edit.html.erb
<div class="box-large-white">
  <h2 class="text-center">Editing Booking</h2>
  <%= render 'form', booking: @booking %>
  <%= link_to 'Back', user_booking_list_path(@booking.user_id)  %>
</div>

app/views/bookings/index.html.erb
<div class='container'>
  <h1><strong>Lista de reservas</strong></h1>
  <h2> Vacancies: <%= @republica.vacancies %></h2>

  <% if @bookings %>
    <div class="republica-container">
      <% @bookings.each do |booking| %>
        <div class="republica-line">
          <div class="republica-image">
            <%= cl_image_tag avatar_image(current_user), width: 100, height: 100, crop: :fill, class: "  dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          </div>
          <div class="republica-content text-center">
            <strong><%= booking.user.first_name %>  <%= booking.user.last_name %></strong> <br>
            Check-in: <%= booking.check_in %><br>
            Check-out: <%= booking.check_out %><br>
            Status: <%= booking.status %><br>
          </div>

          <div class="republica-actions text-center">
            <% if booking.status == "P" %>
              <%= link_to 'Confirm', confirm_republica_booking_path(booking.republica, booking), class: "btn btn-green" %>
              <%= link_to 'Reject', reject_republica_booking_path(booking.republica, booking), class: "btn btn-default" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  <br>

  <%= link_to 'Back', root_path %> |
</div>

app/views/bookings/list_users.html.erb
<div class='container'>
  <h1><strong>Minhas reservas</strong></h1>

  <% if @bookings %>
    <div class="republica-container">
      <% @bookings.each do |booking| %>
        <div class="republica-line">
          <div class="republica-image">
              <%= cl_image_tag booking.republica.photos[0].path, width: 250, height: 150, crop: :fill %>
          </div>
          <div class="republica-content text-center">
            <strong><%= booking.republica.name %> <br>
             <%= booking.republica.address %></strong> <br>
            Check-in: <%= booking.check_in %><br>
            Check-out: <%= booking.check_out %><br>
            Status: <%= booking.status %><br>
          </div>

          <div class="republica-actions text-center">
            <% if booking.status != "A" %>
            <%= link_to 'Edit', edit_republica_booking_path(booking.republica, booking), class: "btn btn-primary" %>
            <% end %>
            <% if booking.status != "C" %>
              <%= link_to 'Cancel', cancel_republica_booking_path(booking.republica, booking), class: "btn btn-default"%>
            <% end %>

          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  <br>

  <%= link_to 'Back', root_path %> |
</div>

app/views/bookings/new.html.erb
<div class="box-large-white">
  <h2 class="text-center">Novo Booking</h2>
  <%= render 'form', booking: @booking %> <br>
  <%= link_to 'Back', republica_bookings_path(@republica), class: "btn btn-default btn-block" %>
</div>

app/views/bookings/show.html.erb
<h1>Show</h1>

<p>
  <Name:>
  <%= @republica.name %>
</p>
<br>

<p>
  <Addres:>
  <%= @republica.address %>
</p>
<br>

<p>
  <Description:>
  <%= @republica.description %>
</p>
<br>

<p>
  <Check-in:>
  <%= @booking.check_in %>
</p>
<br>

<p>
  <Check-ou:>
  <%= @booking.check_out %>
</p>
<br>

<p>
  <Status:>
  <%= @booking.status %>
</p>
<br>


<%= link_to 'Edit', edit_republica_booking_path(@booking) %> |
<%= link_to 'Back', root_path %> |
<%= link_to 'New Booking', new_republica_booking_path(@booking) %>