config/routes.rb
Rails.application.routes.draw do
  # Root path
  root to: "pages#home"

  # User profile
  get '/user/:id', to: 'pages#user', as: 'user'

  # User's bookings path
  get '/user/:id/list_users', to: 'bookings#list_users', as: 'user_booking_list'




  # List of a user's republicas
  get '/republicas/user_republicas', to: 'republicas#user_republicas', as: 'user_republicas'

  # FaceBook connect callback
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Resources path
  resources :republicas do
    resources :bookings do
      member do
        get '/cancel', to: 'bookings#cancel_booking', as: 'cancel'
        get '/confirm', to: 'bookings#confirm_booking', as: 'confirm'
        get '/reject', to: 'bookings#reject_booking', as: 'reject'
      end
    end
  end

  mount Attachinary::Engine => "/attachinary"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-container text-center">
    <ul class="list-inline">
      <li><a href="#"><i class="fa fa-facebook"></i></a></li>
      <li><a href="#"><i class="fa fa-twitter"></i></a></li>
      <li><a href="#"><i class="fa fa-instagram"></i></a></li>
      <li><a href="#"><i class="fa fa-youtube"></i></a></li>
    </ul>
    <p>Coded with <i class="fa fa-heart"></i> in São Paulo</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
<!--     <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
<!--       <%= link_to root_path, class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %> -->

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag avatar_image(current_user), width: 100, height: 100, crop: :fill, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Editar perfil") %>
              <% end %>
            </li>
            <li>
              <%= link_to user_republicas_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Minhas republicas") %>
              <% end %>
            </li>
            <li>
              <%= link_to user_booking_list_path(current_user) do %>
                <i class="fa fa-bed"></i>  <%= t(".profile", default: "Minhas reservas") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Sair") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Nova republica"), new_republica_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
      <% if user_signed_in? %>
        <li><%= link_to "Nova republica", new_republica_path %></li>
        <li><%= link_to "Editar perfil", edit_user_registration_path %></li>
        <li><%= link_to "Minhas republicas", "#" %></li>
        <li><%= link_to "Minhas reservas", "#" %></li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
                  <%= t(".sign_out", default: "Sair") %>
              <% end %>
      <% else %>
        <li><%= link_to "Entrar", new_user_session_path %></li>
      <% end %>
      </ul>
    </div>
  </div>
</div>